### ISSUE TITLE
Always duplicates GCODE and pen_down_angle when should be up

### ISSUE THREAD

**Issue by mssmison** [soukupak/inkscape-unicorn-for-marlin#5]
Using Inkscape 1.0.1 (3bc2e813f5, 2020-09-07) and this works great except for two things:
1. The GCODE is always duplicated, I tried setting copies to 0 but that's not valid.
2. Line 45 of context.py says pen_down_angle when it should be pen_up_angle

Thanks for putting this together.

**Comment by soukupak** [comment]
I know this is almost four years since you created the bug, but I've finally got back to this project and fixed both of those issues. For the second point it was the comment that was wrong, I wanted the pen to go down, but the comment said it will go up, anyway now it's consistent.
Also the plugin should now work with the newest inkscape.
